common/models/Session.php
<?php

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%session}}".
 *
 * @property integer $sessionID
 * @property integer $filmID
 * @property integer $ticketID
 * @property string $date
 * @property string $time_session
 * @property integer $status_session
 *
 * @property Order[] $orders
 * @property Film $film
 * @property Ticket $ticket
 */
class Session extends \yii\db\ActiveRecord
{
	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return '{{%session}}';
	}

	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['filmID', 'ticketID', 'date', 'time_session', 'status_session'], 'required'],
			[['filmID', 'ticketID', 'status_session'], 'integer'],
			[['date', 'time_session'], 'safe'],
			[['filmID'], 'exist', 'skipOnError' => true, 'targetClass' => Film::className(), 'targetAttribute' => ['filmID' => 'filmID']],
			[['ticketID'], 'exist', 'skipOnError' => true, 'targetClass' => Ticket::className(), 'targetAttribute' => ['ticketID' => 'ticketID']],
			[['status_session'], 'default', 'value' => 1]
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'sessionID' => Yii::t('app', 'Session ID'),
			'filmID' => Yii::t('app', 'Film ID'),
			'ticketID' => Yii::t('app', 'Ticket ID'),
			'date' => Yii::t('app', 'Date'),
			'time_session' => Yii::t('app', 'Time Session'),
			'status_session' => Yii::t('app', 'Status Session'),

		];
	}

	public function getFilmsList()
	{
		return ArrayHelper::map(Film::find()->where([
			'status_film' => 1
		])->all(), 'filmID', 'name_film');
	}

	public function getTicketsList()
	{
		return ArrayHelper::map(Ticket::find()->where([
			'status_ticket' => 1
		])->all(), 'ticketID', 'name');
	}


	public function getStatusSession()
	{
		return [
			1 => 'Активно',
			0 => 'Скрыто',
		];
	}

	public function getName()
	{
		return $this->film->name_film . ' ' . $this->date . ' ' . $this->time_session;
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getOrders()
	{
		return $this->hasMany(Order::className(), ['sessionID' => 'sessionID']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getFilm()
	{
		return $this->hasOne(Film::className(), ['filmID' => 'filmID']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getTicket()
	{
		return $this->hasOne(Ticket::className(), ['ticketID' => 'ticketID']);
	}
}

backend/controllers/SessionController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Session;
use common\models\SessionSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SessionController implements the CRUD actions for Session model.
 */
class SessionController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create', 'update', 'delete', 'view', 'index'],
                        'roles' => ['@']
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Session models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SessionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Session model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Session model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Session();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->sessionID]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Session model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->sessionID]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Session model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Session model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Session the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Session::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/SessionController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Session;
use common\models\SessionSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SessionController implements the CRUD actions for Session model.
 */
class SessionController extends \backend\controllers\SessionController
{

	/**
	 * Lists all Session models.
	 * @return mixed
	 */
	public function actionIndex()
	{
		$searchModel = new SessionSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams, 'front');

		return $this->render('index', [
			'searchModel' => $searchModel,
			'dataProvider' => $dataProvider,
		]);
	}

}

backend/views/session/_form.php
<?php

use kartik\date\DatePicker;
use kartik\time\TimePicker;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Session */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="session-form">

	<?php $form = ActiveForm::begin(); ?>

	<?= $form->field($model, 'filmID')->dropDownList($model->filmsList) ?>

	<?= $form->field($model, 'ticketID')->dropDownList($model->ticketsList) ?>

	<?= $form->field($model, 'date')->widget(DatePicker::className(), [
		'name' => 'check_issue_date',
		'convertFormat' => true,
		'options' => ['placeholder' => 'Select issue date ...'],
		'pluginOptions' => [
			'format' => 'php:Y-m-d',
			'todayHighlight' => true
		]
	]) ?>

	<?= $form->field($model, 'time_session')->widget(TimePicker::className(), [
		'name' => 'start_time',
		'value' => '11:24 AM',
		'pluginOptions' => [
			'showSeconds' => true
		]
	]) ?>

	<?= $form->field($model, 'status_session')->dropDownList($model->statusSession) ?>

	<div class="form-group">
		<?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	</div>

	<?php ActiveForm::end(); ?>

</div>

backend/views/session/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\SessionSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="session-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'sessionID') ?>

    <?= $form->field($model, 'filmID') ?>

    <?= $form->field($model, 'ticketID') ?>

    <?= $form->field($model, 'date') ?>

    <?= $form->field($model, 'time_session') ?>

    <?php // echo $form->field($model, 'status_session') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/session/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Session */

$this->title = Yii::t('app', 'Create Session');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Sessions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="session-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/session/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\SessionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Sessions');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="session-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Session'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'label' => Yii::t('app', 'Film'),
                'value' =>function($model, $key, $index, $column) {
                    return $model->film->name_film;
                }
            ],
            [
                'label' => Yii::t('app', 'Ticket'),
                'value' =>function($model, $key, $index, $column) {
                    return $model->ticket->name;
                }
            ],
            [
                'attribute' => 'date',
                'format' => ['date', 'php:Y-m-d']
            ],
            'time_session',
             'status_session',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

backend/views/session/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Session */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Session',
]) . $model->sessionID;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Sessions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->sessionID, 'url' => ['view', 'id' => $model->sessionID]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="session-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/session/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Session */

$this->title = $model->sessionID;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Sessions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="session-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->sessionID], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->sessionID], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'filmID',
            'ticketID',
            [
                'attribute' => 'date',
                'format' => ['date', 'php:Y-m-d']
            ],
            'time_session',
            'status_session',
        ],
    ]) ?>

</div>